### ISSUE TITLE
OpenAI API

### ISSUE THREAD

**Issue by ziyi01** [ziyi01/Inkposter#12]
- [x] Generate theme and prompts in a specified format
   - [x] Process API data
   - [x] Handle errors (faulty request and prompt format) <-- handled by setting status 500, frontend should ask user to try again
- [x] Generate random character names
- [x] Save user stats and theme in mongo
- [x] Restrict generated session prompts based on users previously played sessions

**Comment by gorwat** [comment]
Commit 0597804 solved the last task on this list
