### ISSUE TITLE
[Game logic] Connect parts of host-player presenters, sockets and update model

### ISSUE THREAD

**Issue by ziyi01** [ziyi01/Inkposter#34]
This is what is left from #33, not tested since it is difficult to integrate right now.

``Host-waiting``:
- [x] Call OpenAI
- [x] Select inkposter and distribute prompts
- [x] Update model with sessionData
- [x] Send session data over socket (including role)

``Host-game``:
- [x] Start a timer and end game to redirect when ended
- [x] Make sure player canvas are received
- [x] Make sure all canvases display properly
- [ ] Give visual feedback when player disconnected
- [x] Make sure the canvases don't all end up on a row when playcount gets high

``Host-vote``:
- [x] model needs  updateVoting to save votes and process results
- [x] Broadcast results to all players when all have voted

``Host-end``:
- [x] Process all sessionData into view
- [x] Save to database

``Player-waiting``:
- [x] Update model.roomId in homepage after clicking join

``Player-game``:
Note: I made a file player-game-presenter-real.tsx since I didn't want to touch the other presenter which we are going to rename.
- [x] Create a callback for onChange on sketch-canvas in view to update canvas on host when drawing
- [x] Make sure all relevant data is shown (prompt, if you are impostor, your name)

``Player-vote``:
- [x] Make sure player has access to all relevant data to vote
- [x] Implement onVote with view which takes the votes for theme and inkposter.
- [x] Integrate with view (I don't really understand the props here?)

``Player-end``:
- [x] Player receives result of the game, process if the individual player lost or won (if inkposter or not).
- [x] Not started yet

``Other``:
- [x] Some form of reset should be added
- [x]  Where is persistence done and when do we save the game to the database?
- [x] Restriction of 9 players has to be set

**Comment by gorwat** [comment]
@JuliaHallberg

**Comment by ziyi01** [comment]
Not rendering all canvases correctly cause we don't have login implemented and don't **update model** when player joins/logs in.

**Comment by gorwat** [comment]
Last task "Give visual feedback when player disconnected" migrated to new issue, the rest is done!
