### ISSUE TITLE
[Routes check] Use session details to check if allowed to enter specific pages

### ISSUE THREAD

**Issue by ziyi01** [ziyi01/Inkposter#57]
In `App.tsx`: Maybe need to check `this.host` to disable players from entering `host`-pages and check if `this.roomId` or `socket.rooms` (should be empty) to see if they are connected to a game for the player.

**Comment by gorwat** [comment]
Also

- [ ] Redirect from pages that have nothing (eg /host, /player) 
- [ ] Redirect from game pages if session in not in progress (check if roomId is set), user feedback: "not connected to a session, reloading during will disconnects you from the current session" ish

Redirecting from one game page to another is kind of useless as we dont persist the session, but we could keep track of where in the session we are using cookies and if the player manuelly navigates to somewhere they are not supposed to be, we redirect back to homepage. Would be more worthy to implement if we also persist the sessions.

**Comment by ziyi01** [comment]
Could be worth just setting `/host/game` and `/player/game` to `/host` and `player` so it isn't empty!
