### ISSUE TITLE
Usability stuff

### ISSUE THREAD

**Issue by JuliaHallberg** [ziyi01/Inkposter#71]
Leave game-popup on all game pages (Host)
- [ ] host-game
- [ ] host-session-end
- [ ] host-voting
- [ ] host-waiting

Disconnected stuff:
- [x] Give players a notification if host left the game
- [x] Give user feedback if a player disconnected (grayed out)

Other stuff:
- [x] Player icons
- [ ] Display which players have voted (hostVoting)
- [x] Fix how-to-play text scaling on mobile

**Comment by ziyi01** [comment]
Fix how-to-play text scaling by using responsive design (`sm` and `lg`) in `navbar.tsx`? 
```css
        <div
          className="bg-white dark:bg-gray-800 p-6 rounded shadow-lg sm:w-1/2 lg:w-1/3 mx-auto mt-24 fixed inset-0 flex items-center justify-center overflow-auto"
          onClick={() => setHowToPlayModalOpen(false)}
        >
```
